"""Vendored dependencies for FortifyRoot Ocelle SDK."""
# This package contains vendored copies of OpenLLMetry components.
# Do not modify these files directly - they are generated by vendor_openllmetry.py
